name: Build APK (Buildozer Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display environment info
        run: |
          python3 --version
          java -version
          echo "Working directory: $(pwd)"
          ls -la

      - name: Ensure Buildozer installed
        run: |
          pip install --upgrade pip
          pip install buildozer || true
          buildozer --version

      - name: Set file permissions
        run: chmod -R a+rw .

      - name: Build APK
        run: |
          buildozer android clean || true
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: password-apk
          path: bin/*.apk