name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest
      options: --user root

    env:
      BUILDOZER_ALLOW_ROOT: "1"
      ANDROID_API: "33"
      ANDROID_MINAPI: "21"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer

      - name: Debug environment
        run: |
          echo "BUILDOZER_ALLOW_ROOT=$BUILDOZER_ALLOW_ROOT"
          which python
          buildozer --version

      - name: Clean and build APK
        run: |
          echo "Starting clean and build..."
          BUILDOZER_ALLOW_ROOT=1 buildozer android clean || true
          BUILDOZER_ALLOW_ROOT=1 buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: bin/*.apk