name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    container:
      image: kivy/buildozer:latest
      options: --user root

    env:
      BUILDOZER_ALLOW_ROOT: "1"
      ANDROID_API: "33"
      ANDROID_MINAPI: "21"
      PYTHONPATH: "/usr/local/lib/python3.10/site-packages"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Reinstall Buildozer outside virtualenv
        run: |
          # Remove possible venv
          rm -rf /home/user/.venv
          pip install --upgrade pip
          pip install buildozer==1.5.0

      - name: Debug environment
        run: |
          which buildozer
          buildozer --version
          echo "BUILDOZER_ALLOW_ROOT=$BUILDOZER_ALLOW_ROOT"

      - name: Build APK (skip root prompt)
        run: |
          echo "Starting build..."
          yes | BUILDOZER_ALLOW_ROOT=1 buildozer android clean || true
          yes | BUILDOZER_ALLOW_ROOT=1 buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-apk
          path: bin/*.apk
