name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BUILDOZER_ALLOW_ROOT: 1
      ANDROID_API: 33
      ANDROID_MINAPI: 21
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/27.3.13750724
      ANDROID_NDK: /usr/local/lib/android/sdk/ndk/27.3.13750724

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip python3-setuptools python3-wheel \
            python3-virtualenv libffi-dev libssl-dev libltdl-dev \
            build-essential ccache

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer==1.5.0 cython==0.29.36 python-for-android==2024.4.1 pyjnius==1.5.0

      - name: Prepare environment
        run: |
          echo "Starting clean and build..."
          yes | buildozer android clean || true

      - name: Build APK
        run: |
          yes | buildozer -v android debug
