name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-setuptools \
          python3-wheel \
          python3-virtualenv \
          libffi-dev \
          libssl-dev \
          libltdl-dev

        pip install --upgrade buildozer cython virtualenv

    - name: Build APK
      env:
        BUILDOZER_ALLOW_ROOT: 1
        ANDROID_API: 33
        ANDROID_MINAPI: 21
      run: |
        echo "Starting build..."
        yes | buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
